# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 48e9c7a4a69a052a59a8170bcbb0f053e03c972081eb4894f387f6cfc82000ac67bdea04e27e378fe0a7bba1a889a963f680c75726ef3178c4eaf3e991dcf62d

test:
  secret_key_base: a947636ab8bad84866e81fbf9f6f3d5716ea52fac636b8cec9acea9939f32d4c282e21906cbc3b5711236963417228b989aafc007dbf2393d0a108e6c8e62600

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
